import fs from "node:fs";import https from "node:https";
export type ServiceHealth={name:string,status:"ready"|"unreachable"|"unconfigured";detail:string};
function nodeFetch(url:string,token?:string):Promise<{ok:boolean,status:number}>{return new Promise(resolve=>{try{const u=new URL(url),headers:Record<string,string>={};if(token)headers.Authorization="Bearer "+token;const caPath=process.env.OPENIDENTITY_CONSOLE_CA_CERT;const options:https.RequestOptions={hostname:u.hostname,port:u.port||443,path:u.pathname+u.search,method:"GET",headers,timeout:1500};if(caPath&&fs.existsSync(caPath))options.ca=fs.readFileSync(caPath);const req=https.request(options,res=>{res.resume();resolve({ok:(res.statusCode??500)>=200&&(res.statusCode??500)<500,status:res.statusCode??500});});req.on("timeout",()=>{req.destroy();resolve({ok:false,status:0});});req.on("error",()=>resolve({ok:false,status:0}));req.end();}catch{resolve({ok:false,status:0});}});}
async function probe(name:string,url:string|undefined,token?:string,reachableStatuses:number[]=[200]):Promise<ServiceHealth>{if(!url)return{name,status:"unconfigured",detail:"Not configured"};try{let status=0,ok=false;if(url.startsWith("https://")){const r=await nodeFetch(url,token);status=r.status;ok=reachableStatuses.includes(status);}else{const headers:Record<string,string>={};if(token)headers.Authorization="Bearer "+token;const r=await fetch(url,{headers,cache:"no-store",signal:AbortSignal.timeout(1500)});status=r.status;ok=reachableStatuses.includes(status);}return{name,status:ok?"ready":"unreachable",detail:ok?"Ready":status?"HTTP "+status:"Not reachable"};}catch{return{name,status:"unreachable",detail:"Not reachable"};}}
export async function serviceHealth():Promise<ServiceHealth[]>{return Promise.all([
 probe("Wallet API",process.env.OPENIDENTITY_WALLET_API_HEALTH_URL??(process.env.OPENIDENTITY_WALLET_API_URL??"http://127.0.0.1:9300")+"/ready",process.env.OPENIDENTITY_WALLET_API_TOKEN),
 probe("Verifier",process.env.OPENIDENTITY_VERIFIER_HEALTH_URL??(process.env.OPENIDENTITY_VERIFIER_URL?process.env.OPENIDENTITY_VERIFIER_URL+"/ready":undefined),process.env.OPENIDENTITY_VERIFIER_TOKEN),
 probe("Sui Transport",process.env.OPENIDENTITY_SUI_TRANSPORT_HEALTH_URL??(process.env.OPENIDENTITY_SUI_TRANSPORT_URL?process.env.OPENIDENTITY_SUI_TRANSPORT_URL+"/ready":undefined),process.env.OPENIDENTITY_SUI_TRANSPORT_TOKEN),
 probe("Authorization Server",process.env.OPENIDENTITY_AUTHORIZATION_HEALTH_URL??"http://127.0.0.1:9000/",undefined,[200,302,401,403,404])
]);}