"use client";
import {useState} from "react";import {useRouter} from "next/navigation";
async function action(body:Record<string,unknown>){const r=await fetch("/api/wallet",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.message??data.error??"Wallet action failed");return data;}
export function WalletLockControl({locked}:{locked:boolean}){const router=useRouter(),[open,setOpen]=useState(false),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function unlock(){setBusy(true);setError("");try{await action({action:"unlock",password});setPassword("");setOpen(false);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Unlock failed");}finally{setBusy(false);}}
 async function lock(){setBusy(true);try{await action({action:"lock"});router.refresh();}finally{setBusy(false);}}
 return <>{locked?<button className="app-button primary" onClick={()=>setOpen(true)}>Unlock wallet</button>:<button className="app-button" disabled={busy} onClick={lock}>Lock wallet</button>}{open&&<div className="modal-backdrop" onClick={()=>setOpen(false)}><div className="action-modal" onClick={e=>e.stopPropagation()}><span className="overline">LOCAL WALLET</span><h2>Unlock OpenIdentity</h2><p>Your password is forwarded to the loopback Wallet API for this unlock request. The Console does not persist it.</p><label>Wallet password<input type="password" autoFocus value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==="Enter"&&unlock()}/></label>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button className="app-button" onClick={()=>setOpen(false)}>Cancel</button><button className="app-button primary" disabled={!password||busy} onClick={unlock}>{busy?"Unlocking…":"Unlock wallet"}</button></div></div></div>}</>}

export function CreateAgentControl({locked}:{locked:boolean}){const router=useRouter(),[open,setOpen]=useState(false),[name,setName]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function create(){setBusy(true);setError("");try{await action({action:"createAgent",name});setOpen(false);setName("");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Create failed");}finally{setBusy(false);}}
 return <>{<button className="app-button primary" disabled={locked} title={locked?"Unlock wallet first":""} onClick={()=>setOpen(true)}>Create agent</button>}{open&&<div className="modal-backdrop" onClick={()=>setOpen(false)}><div className="action-modal" onClick={e=>e.stopPropagation()}><span className="overline">NEW AUTONOMOUS ACTOR</span><h2>Create agent identity</h2><p>The agent receives its own OpenIdentity identity and signing key. No authority is delegated yet.</p><label>Agent name<input value={name} onChange={e=>setName(e.target.value)} placeholder="finance-agent"/></label>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button className="app-button" onClick={()=>setOpen(false)}>Cancel</button><button className="app-button primary" disabled={!name||busy} onClick={create}>{busy?"Creating…":"Create agent"}</button></div></div></div>}</>}

export function DelegateControl({locked,agents}:{locked:boolean;agents:string[]}){const router=useRouter(),[open,setOpen]=useState(false),[agent,setAgent]=useState(agents[0]??""),[cap,setCap]=useState("records.read"),[life,setLife]=useState(3600),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function delegate(){setBusy(true);setError("");try{await action({action:"delegate",agentName:agent,capability:cap,lifetimeSeconds:life});setOpen(false);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Delegation failed");}finally{setBusy(false);}}
 return <><button className="app-button primary" disabled={locked||agents.length===0} onClick={()=>setOpen(true)}>Delegate authority</button>{open&&<div className="modal-backdrop" onClick={()=>setOpen(false)}><div className="action-modal" onClick={e=>e.stopPropagation()}><span className="overline">DELEGATED AUTHORITY</span><h2>Grant constrained authority</h2><label>Agent<select value={agent} onChange={e=>setAgent(e.target.value)}>{agents.map(a=><option key={a}>{a}</option>)}</select></label><label>Capability<input value={cap} onChange={e=>setCap(e.target.value)}/></label><label>Lifetime (seconds)<input type="number" min="1" max="86400" value={life} onChange={e=>setLife(Number(e.target.value))}/></label>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button className="app-button" onClick={()=>setOpen(false)}>Cancel</button><button className="app-button primary" disabled={!agent||!cap||busy} onClick={delegate}>{busy?"Delegating…":"Delegate"}</button></div></div></div>}</>}

export function ResetDelegationsControl({locked}:{locked:boolean}){const router=useRouter(),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false),[error,setError]=useState("");
 async function reset(){setBusy(true);setError("");try{await action({action:"resetDelegations"});setConfirm(false);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Reset failed");}finally{setBusy(false);}}
 return <><button className="app-button danger" disabled={locked} onClick={()=>setConfirm(true)}>Reset delegations</button>{confirm&&<div className="modal-backdrop" onClick={()=>setConfirm(false)}><div className="action-modal" onClick={e=>e.stopPropagation()}><span className="overline danger-text">HIGH-IMPACT AUTHORITY CHANGE</span><h2>Reset all delegations?</h2><p>This advances the OpenIdentity state and invalidates grants derived from the previous delegation generation. Fresh OAuth authority from stale grants will be rejected.</p>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button className="app-button" onClick={()=>setConfirm(false)}>Cancel</button><button className="app-button danger" disabled={busy} onClick={reset}>{busy?"Resetting…":"Reset delegations"}</button></div></div></div>}</>}